### ISSUE TITLE
Bug: error suggesting policies when "default" namespace is chosen

### ISSUE THREAD

**Issue by roopeshsn** [deggja/netfetch#121] opened 2024-02-04 16:30 UTC
Application throws an error when selecting the `default` namespace and clicking the `Suggest policies` button,
```
App.vue:525 Error suggesting policies: TypeError: Cannot read properties of null (reading 'app.kubernetes.io/name')
    at App.vue:541:29
    at Array.forEach (<anonymous>)
    at Proxy.suggestNetworkPolicy (App.vue:540:17)
    at Proxy.suggestPolicy (App.vue:513:40)
```
![netfetch-dashboard-bug](https://github.com/deggja/netfetch/assets/70762571/65a39f40-10b6-488c-ae37-e60ed7d4e124)

**Comment by deggja** [comment] 2024-02-04 18:14
Thanks for trying the app and creating the issue!

I will take a look at this as soon as possible. Should be a relatively easy fix.

**Comment by deggja** [comment] 2024-02-09 21:03
@roopeshsn Could you provide some more details as to how to reproduce this? I'm not getting these errors in my clusters.

**Comment by roopeshsn** [comment] 2024-02-10 03:25
This is weird. I tried to reproduce but this time no error was thrown.

**Comment by deggja** [comment] 2024-02-10 11:33
> This is weird. I tried to reproduce but this time no error was thrown.

Hmm. Might have stumbled on some type of corner case here. I suggest we close this issue and reopen it if it reappears.

**Comment by deggja** [comment] 2024-02-11 14:37
Closing issue as we are not able to reproduce.

**Closed by deggja** 2024-02-11 14:37 UTC
